[target.aarch64-linux-android]
linker = "/home/albert/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"

[env]
CC_aarch64_linux_android = "/home/albert/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"
AR_aarch64_linux_android = "/home/albert/Android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
